---
name: Selenium CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: temurin
          cache: maven

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: List files in workspace (Diagnostic)
        run: ls -R

      - name: Run Maven Tests
        run: |
          cd xAmplifyQA  # Navigate to directory containing pom.xml
          mvn clean install

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: xAmplifyQA/target/surefire-reports  # Adjusted path to reflect directory change
